import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import { ContentScheduler } from '@/lib/scheduler'
import { z } from 'zod'

const AutoScheduleSchema = z.object({
  daysToSchedule: z.number().min(1).max(90).default(30),
  maxPostsPerDayPerChannel: z.number().min(1).max(10).default(2),
  avoidConsecutiveSameTag: z.boolean().default(true),
  channelIds: z.array(z.string()).optional(), // If provided, only schedule for these channels
  clearExisting: z.boolean().default(false), // Whether to clear future unscheduled slots
})

// POST /api/schedule/auto - Auto-generate publishing schedule
export async function POST(request: NextRequest) {
  try {
    const body = await request.json()
    const validated = AutoScheduleSchema.parse(body)

    // Get all READY content items
    const where: any = { status: 'READY' }
    if (validated.channelIds && validated.channelIds.length > 0) {
      where.targetChannelId = { in: validated.channelIds }
    }

    const readyItems = await prisma.contentItem.findMany({
      where,
      include: {
        targetChannel: true,
      },
    })

    if (readyItems.length === 0) {
      return NextResponse.json(
        { message: 'No READY content items to schedule', slotsCreated: 0 },
        { status: 200 }
      )
    }

    // Create scheduler with rules
    const scheduler = new ContentScheduler({
      daysToSchedule: validated.daysToSchedule,
      maxPostsPerDayPerChannel: validated.maxPostsPerDayPerChannel,
      avoidConsecutiveSameTag: validated.avoidConsecutiveSameTag,
    })

    // Generate schedule
    const schedule = scheduler.generateSchedule(readyItems)

    // Clear existing future slots if requested
    if (validated.clearExisting) {
      await prisma.publishingSlot.deleteMany({
        where: {
          scheduledAt: {
            gte: new Date(),
          },
          contentItemId: null, // Only clear empty slots
        },
      })
    }

    // Create publishing slots in database
    const createdSlots = await prisma.$transaction(
      schedule.map(slot =>
        prisma.publishingSlot.create({
          data: {
            channelId: slot.channelId,
            scheduledAt: slot.scheduledAt,
            contentItemId: slot.contentItemId,
            metaJson: { autoGenerated: true },
          },
        })
      )
    )

    // Update content items to SCHEDULED status
    await prisma.contentItem.updateMany({
      where: {
        id: {
          in: schedule.map(s => s.contentItemId),
        },
      },
      data: {
        status: 'SCHEDULED',
      },
    })

    const score = scheduler.scoreSchedule(schedule)

    return NextResponse.json({
      message: 'Schedule generated successfully',
      slotsCreated: createdSlots.length,
      itemsScheduled: readyItems.length,
      score,
      dateRange: {
        start: schedule[0]?.scheduledAt,
        end: schedule[schedule.length - 1]?.scheduledAt,
      },
    })
  } catch (error) {
    if (error instanceof z.ZodError) {
      return NextResponse.json(
        { error: 'Validation error', details: error.errors },
        { status: 400 }
      )
    }
    console.error('Error generating schedule:', error)
    return NextResponse.json(
      { error: 'Failed to generate schedule' },
      { status: 500 }
    )
  }
}
